# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import *
from PyQt5.QtCore import QUrl
from MyProject.pac.RunTo.DiagramMaker import *
import os

class Ui_subForm_2(QtWidgets.QWidget, object):
    def __init__(self):
        super(Ui_subForm_2, self).__init__()
        self.setupUi(self)
        self.initUI()
        self.DataPath = ''
    def setupUi(self, subForm_2):
        subForm_2.setObjectName("subForm_2")
        subForm_2.resize(731, 531)
        self.frame = QtWidgets.QFrame(subForm_2)
        self.frame.setGeometry(QtCore.QRect(20, 30, 701, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 20, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 341, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(50, 70, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 70, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(520, 70, 141, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(subForm_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 701, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")


        self.retranslateUi(subForm_2)
        QtCore.QMetaObject.connectSlotsByName(subForm_2)

    def initUI(self):
        self.webViewSettings = QWebEngineSettings.globalSettings()
        self.webViewSettings.setAttribute(QWebEngineSettings.JavascriptEnabled, True)
        self.webViewSettings.setAttribute(QWebEngineSettings.JavascriptCanOpenWindows, True)
        self.webViewSettings.setAttribute(QWebEngineSettings.PluginsEnabled, True)

        self.webView = QWebEngineView()
        self.webView.load(QUrl(r'E:/Diplomat_Project/render.html'))
        self.horizontalLayout.addWidget(self.webView)
        self.lineEdit.setText(os.getcwd())
        self.pushButton_3.clicked.connect(self.chose_file_path)
        self.pushButton.clicked.connect(self.DiagramOfSector)

    def retranslateUi(self, subForm_2):
        _translate = QtCore.QCoreApplication.translate
        subForm_2.setWindowTitle(_translate("subForm_2", "Form"))
        self.pushButton_3.setText(_translate("subForm_2", "打开数据"))
        self.label_2.setText(_translate("subForm_2", "数据路径："))
        self.pushButton.setText(_translate("subForm_2", "扇形图1"))
        self.pushButton_2.setText(_translate("subForm_2", "折线图"))
        self.pushButton_4.setText(_translate("subForm_2", "散点图"))

    def testButton(self):
        _url = r'E:/Diplomat_Project/render.html'
        baidu_url = "https://www.baidu.com"
        self.webView.load(QUrl(_url))

    def chose_file_path(self):
        curPath = os.getcwd()
        Path = QtWidgets.QFileDialog.getOpenFileName(self, 'Open Data File', curPath,
                                                     "Data File(*.csv;*.xls);;")
        FILE_PATH = Path[0]
        self.lineEdit.setText(FILE_PATH)

    # 扇形图
    def DiagramOfSector(self):
        DataFile = self.lineEdit.text()
        print(DataFile)
        sdg = SectorDiagramMaker(str(DataFile))
        FinalData = sdg.get()
        print("-------")
        print(FinalData)
        # self.webView.load(QUrl(FinalData))

